### PR TITLE
Copied relevant changes from Implement_DOI. Rebuilt Manual.

### PR DESCRIPTION
**Pull request by jcrozum**

### CODE REVIEW

**Comment by jcrozum** [comment]
I changed the testing file to point to the functions from `DomainOfInfluence.py` instead of redefining the functions in the testing file itself. Please double check that it still works.

**Review by kyuhyongpark — CHANGES_REQUESTED** [review]
Everything looks good, but the testing file needs
import itertools as it

**Comment by jcrozum** [comment]
I've added that import. If everything looks good to you, can you complete the review and merge the branch?

**Review by kyuhyongpark — APPROVED** [review]
Everything looks good.

**Pull request merged**
